package de.freesoccerhdx.pandadb;

public enum Status {

    SUCCESSFUL_SET,
    SUCCESSFUL_GET_DATA,
    SUCCESSFUL_GET_KEYS,
    SUCCESSFUL_CLEARED,
    SUCCESSFUL_CREATED_NEW,
    SUCCESSFUL_REMOVED_KEY,
    SUCCESSFUL_REMOVED_MEMBER,
    SUCCESSFUL_OVERWRITE_OLD,
    SUCCESSFUL_ADD_ENTRY,
    SUCCESSFUL_REMOVED_LISTTYPE,
    SUCCESSFUL_GET_LISTINDEX,


    INDEX_NOT_FOUND,
    KEY_NOT_FOUND,
    KEY_ALREADY_EXISTS,
    LISTTYPE_NOT_FOUND,
    LISTKEY_NOT_FOUND,
    SUCCESSFUL_REMOVED_LISTKEY,
    SUCCESSFUL_REMOVED_LISTINDEX,
    NO_KEYS_AVAILABLE,
    MEMBER_NOT_FOUND;


    public boolean isSuccessful(){
        return this.name().startsWith("SUCCESSFUL");
    }

}
